FROM quay.io/astronomer/astro-runtime:11.0.0

USER root
RUN apt-get update && apt-get install -y git ssh && rm -rf /var/lib/apt/lists/*
USER astro

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY airflow /usr/local/airflow
WORKDIR /usr/local/airflow
